### ISSUE TITLE
Special chars in books search cause error.

### ISSUE THREAD

**Issue by none23** [vercel-labs/book-inventory#8]
https://next-books-search.vercel.app/?q=%26
![image](https://github.com/user-attachments/assets/9d698af4-5ae7-40b0-8bae-365c7454b236)

**Comment by leerob** [comment]
Working now!
![CleanShot 2024-08-16 at 14 09 39@2x](https://github.com/user-attachments/assets/2de35dbf-46fb-430f-a010-0763da2120e8)
